version: '3'
services:
  services1:
    image: quangno129/swarmtest:node
    networks:
      - net2
    ports:
      - 8085:8085
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure
  services2:
    image: quangno129/swarmtest:dotnet
    networks:
      - net2
    ports:
      - 8086:8085
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure
networks:
  net2:
    driver: overlay